/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fancyhotels;

import Entities.Customer;
import Entities.Room;
import Entities.Reservation;
import java.util.ArrayList;
import java.sql.Date;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;

/**
 *
 * @author pwilson3
 */
public class CancelReservation extends javax.swing.JFrame {
    private Customer user;
    FancyHotelSingleton singleton;
    private static String cancelID;

    /**
     * Creates new form CancelReservation
     */
    public CancelReservation() {
        this.user = user;
        singleton = FancyHotelSingleton.getInstance();
        initComponents();
        /*try{
            ArrayList<Room> availableRooms = singleton.findRooms(resID);
            DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
            model.setRowCount(0);
            for (Room room: availableRooms) {
                model.addRow(new Object[]{room.getRoomNumber(),
                    room.getRoomCategory(),room.getNumPeople(),
                    room.getCostPerDay(),room.getExtraBedCost()});
            }
        }catch(Exception e){
             System.out.println("Exception: " + e);
        }*/
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        reservationCostTextfield = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cancelButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        startDateTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        reservationIDTextfield = new javax.swing.JTextField();
        endDateTextfield = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cancellationDateTextfield = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        refundAmountTextfield = new javax.swing.JTextField();
        getResButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Room #", "Room Category", "# Persons Allowed", "Cost Per Day", "Cost of Extra Bed per Day", "Select Extra Bed"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Float.class, java.lang.Float.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        reservationCostTextfield.setEditable(false);
        reservationCostTextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservationCostTextfieldActionPerformed(evt);
            }
        });

        jLabel7.setText("Total Cost of Reservation");

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Start Date");

        startDateTextField.setEditable(false);
        startDateTextField.setText("0000-00-00");
        startDateTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startDateTextFieldActionPerformed(evt);
            }
        });

        jLabel1.setText("Reservation ID");

        reservationIDTextfield.setText("12345");
        reservationIDTextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservationIDTextfieldActionPerformed(evt);
            }
        });
        reservationIDTextfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                reservationIDTextfieldKeyPressed(evt);
            }
        });

        endDateTextfield.setEditable(false);
        endDateTextfield.setText("0000-00-00  ");
        endDateTextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endDateTextfieldActionPerformed(evt);
            }
        });

        jLabel3.setText("End Date");

        jLabel8.setText("Date of Cancellation");

        cancellationDateTextfield.setEditable(false);
        cancellationDateTextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancellationDateTextfieldActionPerformed(evt);
            }
        });

        jLabel9.setText("Amount to be Refunded");

        refundAmountTextfield.setEditable(false);
        refundAmountTextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refundAmountTextfieldActionPerformed(evt);
            }
        });

        getResButton.setText("Get Reservation");
        getResButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getResButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(cancellationDateTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(reservationCostTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(refundAmountTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(137, 137, 137))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(232, 232, 232)
                                .addComponent(cancelButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(18, 18, 18)
                                        .addComponent(reservationIDTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(startDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel3)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(endDateTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(46, 46, 46)
                                        .addComponent(getResButton)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(reservationIDTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(getResButton)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(startDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(endDateTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(reservationCostTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cancellationDateTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(refundAmountTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelButton)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void reservationCostTextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservationCostTextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reservationCostTextfieldActionPerformed

    private void reservationIDTextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservationIDTextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reservationIDTextfieldActionPerformed

    private void endDateTextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endDateTextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_endDateTextfieldActionPerformed

    private void cancellationDateTextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancellationDateTextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancellationDateTextfieldActionPerformed

    private void refundAmountTextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refundAmountTextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_refundAmountTextfieldActionPerformed

    private void reservationIDTextfieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_reservationIDTextfieldKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_reservationIDTextfieldKeyPressed

    private void getResButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getResButtonActionPerformed
            // TODO add your handling code here:
            this.cancelID = reservationIDTextfield.getText();
            Integer intID = Integer.parseInt(cancelID.trim());
            try {
                Reservation res = singleton.getReservation(intID);
                startDateTextField.setText(res.getStartDate().toString());
                endDateTextfield.setText(res.getEndDate().toString());
                reservationCostTextfield.setText(Float.toString(res.getTotalCost()));
                
                ArrayList<Room> reserved = singleton.getCustomerReservations(
                        intID);

                DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
                model.setRowCount(0);
                for (Room room: reserved){
                    model.addRow(new Object[]{room.getRoomNumber(),
                    room.getRoomCategory(),room.getNumPeople(),
                    room.getCostPerDay(),room.getExtraBedCost()});
                }
            SimpleDateFormat form = new SimpleDateFormat("yyyy-MM-dd");
            java.util.Date today = new java.util.Date();
            String now = form.format(today);
            cancellationDateTextfield.setText(now);
            float daysBefore = singleton.countDays(now, res.getStartDate().toString());
            if (daysBefore == 1.0f){
                refundAmountTextfield.setText("0");
            }else if(daysBefore >= 2.0f && daysBefore <= 3.0f){
                refundAmountTextfield.setText(Float.toString(res.getTotalCost() * 0.2f));
            }else if(daysBefore > 3.0f){
                refundAmountTextfield.setText(Float.toString(res.getTotalCost() * 0.8f));
            }else {
                refundAmountTextfield.setText("Not Allowed");
            }
            
            } catch (Exception e){
                System.out.println("Error " + e);
            }
            
            
    }//GEN-LAST:event_getResButtonActionPerformed
  
    private void startDateTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startDateTextFieldActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_startDateTextFieldActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        if(!refundAmountTextfield.getText().equals("Not Allowed"))
            singleton.cancelReservation(cancelID);
    }//GEN-LAST:event_cancelButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CancelReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CancelReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CancelReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CancelReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CancelReservation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField cancellationDateTextfield;
    private javax.swing.JTextField endDateTextfield;
    private javax.swing.JButton getResButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField refundAmountTextfield;
    private javax.swing.JTextField reservationCostTextfield;
    private javax.swing.JTextField reservationIDTextfield;
    private javax.swing.JTextField startDateTextField;
    // End of variables declaration//GEN-END:variables
}
